spring:
  application:
    name: "configserver"
  profiles:
    #active: native
    active: git
  cloud:
    config:
      server:
        #native:
          #search-locations: "file:///D://2025//COURSES//Tests//config"
        #search-locations: "classpath:/config"
        git:
          uri: "https://github.com/singhgurpreetcs/microservices_config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
server:
  port: 8071


